<?php

namespace SiteStyleBundle\Repository;

/**
 * SocialMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
